### ISSUE TITLE
ParameterReader API change breaks large set of repos

### ISSUE THREAD

**Issue by mm318** [aws-robotics/utils-common#15]
https://github.com/aws-robotics/utils-common/commit/919d1756bffbb733a8b1937c3442b6fc94fde69e is an backwards incompatible change that affected numerous repos under https://github.com/aws-robotics.

**Comment by mm318** [comment]
The rollout process of backward incompatible changes need to be improved for the future.

**Comment by nburek** [comment]
This is primarily an issue because the master branch is loosely considered the release branch for now. We are in the process of rolling back this change to unblock builds for packages that depend on this package. We will then create a release version of all of our packages and update our documentation so that it is clear how to get and pull the latest release versions of our code. At that point we will be able to push forward on backwards incompatible changes.

**Comment by nburek** [comment]
Closing this as all the repositories have been reverted. We are updating them all to have a release branch before we roll forward any more breaking changes.
